# Generated by Django 3.1.7 on 2021-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='Reason',
            field=models.CharField(default='aucun', max_length=50, null=True),
        ),
        migrations.RenameField('Call', 'is_Present', 'is_Missing'),
    ]
