# Generated by Django 3.1.7 on 2021-04-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_call_reasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
    ]
