# Generated by Django 3.1.7 on 2021-04-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_call_cursus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='cursus',
        ),
    ]
