# Generated by Django 3.1.7 on 2021-04-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0008_generalcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='generalCall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.generalcall'),
        ),
    ]
