# Generated by Django 3.1.5 on 2021-04-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0009_call_generalcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='Date',
            field=models.DateField(help_text='yyyy-mm-ddd', null=True),
        ),
        migrations.AlterField(
            model_name='generalcall',
            name='Date',
            field=models.DateField(help_text='yyyy-mm-ddd', null=True),
        ),
    ]
